meta_product_name: "Neighborfood"
meta_title: "Neighborfood - Mon voisin est un Chef!"
meta_description: "Réserver votre plat du soir à l'un des nombreux chefs cuistots de votre quartier !,  Avec neighborfood, rencontrez vos voisins et découvrez de nouvelles saveurs à des prix raisonnables"
meta_image: "neighborfood.png" # should exist in `app/assets/images/`

